### ISSUE TITLE
Not working with Nuxt.js out of the box, error: Unexpected token .

### ISSUE THREAD

**Issue by IlyaSemenov** [mirari/v-viewer#22]
## Problem

`require("viewerjs/dist/viewer.css")` inside compiled module crashes when running in Nuxt.js webpack environment (and possibly many others).

## Steps to reproduce

This recreates full test environment completely from scratch:

```bash
mkdir viewtest
cd viewtest
yarn init .
yarn add nuxt v-viewer
```

create `pages/index.vue`:

```vue
<template>
<div v-viewer>
	<img src="https://lorempixel.com/600/400/">
	<img src="https://lorempixel.com/400/600/">
</div>
</template>

<script>
import Vue from 'vue'
import Viewer from 'v-viewer'
Vue.use(Viewer)

export default {}
</script>
```

Run server:

```bash
node_modules/.bin/nuxt
```

Open http://localhost:3000, the following error will be printed:

```
  nuxt:render Rendering url / +0ms
{ /Users/semenov/tmp/viewtest/node_modules/viewerjs/dist/viewer.css:11
.viewer-zoom-in::before,
^

SyntaxError: Unexpected token .
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at webpackUniversalModuleDefinition (/Users/semenov/tmp/viewtest/node_modules/v-viewer/dist/v-viewer.js:3:49)
    at Object.<anonymous> (/Users/semenov/tmp/viewtest/node_modules/v-viewer/dist/v-viewer.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12) statusCode: 500, name: 'SyntaxError' }
```

## Other notes

It is not as simple as CSS loader not being enabled. requiring css from the component script tag works fine:

```vue
<script>
require("viewerjs/dist/viewer.css")

export default {}
</script>
```

- this works and will actually push CSS into the page.

**Comment by mirari** [comment]
I think it's unnecessary to import css file automatically now, someone may want to customize the style,  and the css importing script built by webpack may not support requirejs, so I deleted it.
1.0.0 released. 
Now you can and you have to import the css file by yourself.
Please try it and give me a reply, thank you.

**Comment by IlyaSemenov** [comment]
It works now, thanks.
